- root/etc/logrotate.d/firewall
**Issue found on v7.**
root got an email with the following content:
/etc/cron.daily/logrotate:
error: stat of /var/log/firewall.log failed: No such file or directory
The firewall.log file was really missing.
> firewall log rotation: add missingok directive to avoid error mail

- root/etc/e-smith/templates/etc/shorewall/policy/20policy
- root/etc/e-smith/templates/etc/shorewall/policy/40policy_static
- root/etc/e-smith/templates/etc/shorewall/rules/10base20established
- root/etc/e-smith/templates/etc/shorewall/rules/10base50related
- root/etc/e-smith/templates/etc/shorewall/rules/20ping
- root/etc/e-smith/templates/etc/shorewall/rules/30dns
- root/etc/e-smith/templates/etc/shorewall/rules/60rules
- root/etc/e-smith/templates/etc/shorewall/rules/70services
NethServer/dev#5104
When NFQ is enabled, an ACCEPT rule with logging enabled raises this Shorewall warning:
> Checking /etc/shorewall/action.NFQBY for chain %NFQBY...
>    WARNING: Log Prefix shortened to "Shorewall:NFQBY:IPTABLES(NFQ " /etc/shorewall/action.NFQBY (line 2)
>       from /etc/shorewall/rules (line 111)
We can avoid the warnings following this steps:
- in `shorewall.conf `change `LOGFORMAT` to `"FW:%s:%s:"`
- in `/etc/rsyslog.d/shorewall.conf` change the matching regexp
> Force all traffic through NFQ, if nfqueue is enabled

- README.rst
- root/etc/e-smith/templates/etc/shorewall/mangle/20ndpi
- root/etc/e-smith/templates/etc/shorewall/mangle/40priorities
- root/etc/e-smith/templates/etc/shorewall/mangle/60providers
Assumptions and limitations
1. All nDPI traffic is marked in forward chain
2. Priority rules are in post chain and can use nDPI markers
If a priority rule uses a role (interface) as source, the rule can't be added to postrouting chain since the packet is already natted: Shorewall will move the rule on top of forwarding chain
3. nDPI rules can't block the http/https traffic if web proxy is enabled in transparent mode
4. All nDPI markers are read from /proc/net/xt_ndpi/proto and shifted by 8 bits
5. Divert rules can't be used with nDPI, because an established TCP connection can't be moved between providers
NethServer/dev#5113
> Traffic shaping: refactor rule order

- root/usr/libexec/nethserver/initialize-fwservices-database
Rely on the undocumented esmith::DB feature that runs an external script when a database is created for the first time.
> Initialize fwservices with default records

- createlinks
Index 99 is reserved for nethserver-backup-{config,data}
packages to close the restore transanction.
NethServer/dev#5343
> post-restore: move last actions to index 98

- root/etc/e-smith/events/actions/nethserver-firewall-base-disable
- root/etc/e-smith/events/actions/nethserver-firewall-base-enable
- root/etc/e-smith/events/actions/nethserver-shorewall-restart
Add support for masked unit to nethserver-shorewall-restart action
Unit are masked with symlinks under ``/run``. The masked state is lost after reboot. This solution does not alter the DB.
NethServer/dev#5343
> Mask shorewall unit during ns6upgrade

- root/etc/e-smith/events/actions/interface-config-write-pppoe
This makes sure that the machine keeps trying
to connect forever after pppoe-start is called
NethServer/dev#5358
> pppoe: change connect_timeout to 0

- root/usr/share/nethesis/NethServer/Module/Nat.php
All host objects must be expressed in the form 'host;<name>'
to be correctly translated by the NethServer::Firewall perl library.
Before the fix, hosts with DHCP reservation were
referenced using the format 'local;<name>'
NethServer/dev#5417
> sNAT UI: always use 'host' object type

- root/usr/share/nethesis/NethServer/Module/FirewallRules/Index.php
nDPI 2.2 uses camel case protocol names, while icons name are lowercase
> UI: fix icon lookups

- createlinks
- root/etc/e-smith/templates/etc/shorewall/helpers/10base
- root/etc/e-smith/templates/etc/shorewall/helpers/20helpers
- root/etc/e-smith/templates/etc/shorewall/helpers/30log
Avoid warning at startup:
kernel: ipt_ULOG: ULOG: fail to register logger.
NethServer/dev#5490
> shorewall: do not load ipt_ULOG kernel module

- root/etc/e-smith/templates/etc/firehol/fireqos.conf/10base
- root/etc/e-smith/templates/etc/firehol/fireqos.conf/20rules
Set FIREQOS_CONNMARK_RESTORE="act_connmark" only
if running kernel supports it.
Installations with old kernel will still work even without reboot.
Thanks to @filippocarletti 
NethServer/dev#5484
> fireqos: dynamically set act_connmark

- NethServer/Firewall.pm
Better solution is to update the NetAddr::IP library (https://metacpan.org/pod/NetAddr::IP) to the latest version and use the `:noqfdn` option.
But CentOS provides an older version which doesn't have such option.
See also http://dev.nethserver.org/issues/3056
NethServer/dev#5625
> firewall lib: prevent zone name resolution

- root/etc/e-smith/templates/etc/shorewall/mangle/80qos_fw
NethServer/dev#5642
Squid can mark outgoing packets, we have to save the marks to shape
incoming traffic.
> Save packet marks for traffic from the firewall

- createlinks
- root/etc/e-smith/events/actions/nethserver-firewall-adjustdb
If an interface becomes part of a logical interface its firewall zone
records are transferred to the logical interface.
The logical interface deletion is implemented by https://github.com/NethServer/nethserver-base/pull/144
NethServer/dev#5637
> Adjust zone record references

- nethserver-firewall-base.spec
Previously the Cockpit UI was present even if nethserver-firewall-base-ui wasn't installed.
The API is still inside nethserver-firewall-base package because it could be useful for automation.
> spec: exclude Cockpit UI from base package

- ui/src/views/Settings.vue
Without this patch the setting page can't be edit from non-root users.
> Sudo permission for settings delegation

- ui/src/views/LocalRules.vue
- ui/src/views/PortForward.vue
- ui/src/views/Rules.vue
- ui/src/views/TrafficShaping.vue
- ui/src/views/WAN.vue
- Added "edit rule" in the kebab menu of these pages:
- Local rules
- Rules
- Traffic shaping
- WAN
- Port forward
- Fixed port forwarding input form: while editing a port forward that uses a protocol different from TCP/UDP, source port and destination port inputs are now disabled
- Fixed port forwarding: disabling a rule now data is preserved and managed as expected
> Firewall August fixes

- root/etc/e-smith/templates/etc/shorewall/rules/50pf
Port forward rules on protocols such as AH, GRE and ESP are now included in Shorewall rules template.
> Port forward for non-TCP/UDP protocols

- ui/src/views/TrafficShaping.vue
Priority rules table now shows appropriate icons for L7 applications
https://github.com/NethServer/dev/issues/5846
> Fixed icons for L7 apps in traffic shaping

- ui/src/views/Settings.vue
- **MAC validation (IP/MAC binding)** now reflects `MACValidation` property value
- Changed label _Allowed_ to _Enabled_ for **MAC validation (IP/MAC binding)** toggle
https://github.com/NethServer/dev/issues/5879
> Fixed MAC validation toggle

- ui/public/i18n/language.json
- ui/src/views/Settings.vue
Informative description for MAC validation (IP/MAC binding) controls:
- **MAC validation** toggle switch
- **MAC validation policy** checkbox
Improved label text for **MAC validation policy** checkbox
https://github.com/NethServer/dev/issues/5883
> Informative description for MAC validation (IP/MAC binding)

- NethServer/Firewall.pm
Avoid enabling ndpi rules if something failed during kernel module
update.
This workaround should avoid ndpi version mismatch between kernel module
and user space libraries.
NethServer/dev#5890
> firewall lib: check for ndpi lock

- ui/src/views/TrafficShaping.vue
FireQOS uses kpbs unit for "kilobytes per second" instead
of "kilobits per second".
Bandwidth should be always expressed in kilobits.
NethServer/dev#5897
> ui: use kbit unit for tc classes

- NethServer/Database/Ndpi.pm
Avoid warning on /etc/shorewall/mangle template:
Use of uninitialized value $count in concatenation (.) or string at
/usr/share/perl5/vendor_perl/NethServer/Database/Ndpi.pm line 41, <$fh> line 308
> ndpi lib: suppress warning

- root/etc/e-smith/events/actions/providers-cleanup
When a red interface is deleted, the status file is retained
under /var/lib/shorewall directory.
Remove the stale status file, so the interface
is no more listed when executing 'shorewall status -i'
> save event: cleanup stale status files

- root/etc/e-smith/templates/etc/shorewall/rules/50pf
Hairpin implementation was missing the snat part and
never worked nor on blue nor on orange.
NethServer/dev#6045
> port forward: remove hairpin for blue and orange zones

- createlinks
- root/etc/e-smith/events/actions/nethserver-firewall-base-network-reset
Delete dangling objects and disable rules with not-existing objects
See NethServer/nethserver-backup-config#41
NethServer/dev#6099
> post-restore: support skip-network option

- root/etc/e-smith/events/actions/providers-cleanup
Delete also the status referring to existing
network interface but with a non-red role.
NethServer/dev#6105
> providers: cleanup stale status

- root/etc/e-smith/events/actions/nethserver-shorewall-wan-update
Clean up default route when a firewall restarts after all providers have
been set to disabled.
This is a fix for a corner case. Conditions to reproduce the problem:
- 2 or more WAN providers configured in active-backup mode
- both providers should be disabled
- reboot the firewall while all providers are still disabled
NethServer/dev#6157
> wan-update: restart shorewall if needed

- root/etc/e-smith/templates/etc/shorewall/rules/50pf
- root/etc/e-smith/templates/etc/shorewall/snat/51pflanmasq
I have 2 major doubts on this PR:
- ~~OpenVPN traffic should already work and~~ no SNAT should be needed
- with this change in place, access to hosts inside blue and orange will still work but always without SNAT, which I think should be required (at lease following [shorewall doc](https://shorewall.org/FAQ.htm#DNS-DNAT))
NethServer/dev#6165
> Enable hairpin NAT for OpenvPN RW

- root/etc/e-smith/templates/etc/shorewall/mangle/40priorities
Write rules in tcpost (mangle) in the same order they are displayed  in the web UI.
NethServer/dev#6203
> Remove reverse order for QoS Rules

- root/etc/e-smith/templates/etc/shorewall/mangle/20ndpi
This will fix inbound traffic shaping for traffic to the firewall itself.
It adds a CONNMARK restore in the mangle INPUT chain.
> Restore connmark for traffic to the firewall

- ui/public/i18n/language.json
This is how the dashboard looks like:
NethServer/dev#6206
> ui: add missing label

- NethServer/Firewall.pm
- README.rst
- api/objects/create
- api/objects/delete
- api/objects/read
- api/objects/validate
- createlinks
- ui/public/i18n/language.json
- ui/src/views/Objects.vue
- ui/src/views/Rules.vue
This PR adds 2 features:
- allow creation of firewall rules using MAC address objects
- allow creation of firewall rules which apply also on established and related connections
- Create a MAC object:
```
db macs set m1 mac Address '52:54:00:05:2d:c3' Description 'test' Zone green
```
- Create a rule using an host object from the web interface, then modify it from command line:
```
db fwrules setprop 1 Src 'mac;m1'
```
- Apply the configuration:
```
signal-event firewall-adjust
```
- firewall object page: CRUD operations for MAC address objects
- rules page: allow the selection of MAC objects inside the source field
Validation rules:
- rules: a MAC object can't be used as destination
- object: Address and Zone property are mandatory
NethServer/dev#6269
> Support MAC address objects inside firewall rules

- README.rst
- api/lib/firewall_functions
- api/lib/firewall_functions.php
- root/etc/e-smith/templates/etc/shorewall/rules/10base15rules
- ui/public/i18n/language.json
- ui/src/views/Rules.vue
A rule can now be placed under the "ALL" or "NEW" section inside the
/etc/shorewall/rules file.
Allow creation of firewall rules which apply also on established and related connections.
The combination of this PR with #151 will permit to quickly block the traffic from an hostile host inside the LAN.
- Create a rule from the web interface, then modify it from command line:
```
db fwrules setprop 1 State all
```
- Apply the configuration:
```
signal-event firewall-adjust
```
- rules page: add a new checkbox inside the advanced section, something like `Apply rule to existing connections`
- rules page: allow the `any` target for source and destination to support traffic blocking from hosts identified only by MAC addresses
- rules page: highlight rules with State all inside the list view …
> rules: add connection state support

- api/objects/validate
Fix validation for MAC object edit.
Validation ensures that MAC address is not already used by another MAC object
NethServer/dev#6269
> Fix validation for MAC address

- ui/src/views/WAN.vue
When you create a rule in the WAN firewall application you have an issue about undefined values
see also https://trello.com/c/875GDc41/232-bug-su-wan-e-policy-route
https://github.com/NethServer/dev/issues/6289
> Fix undefined value to create object in WAN rule

- api/objects/create
Support only lower case MAC address.
If the MAC address is saved on upper case, the firewall library
can't correctly find the zone of the host.
NethServer/dev#6377
> MAC objects: force lower case

- api/wan/read
- ui/src/views/WAN.vue
this PR intends to fix
- the multiple instances running at the same time
- a `/s` to the value of download/upload
- avoid to reload the web page if you want to make a new test
https://github.com/NethServer/dev/issues/6385
> Restart speedtest each time needed

- ui/src/views/TrafficShaping.vue
Fix unit of measurement in traffic shaping bandwidth chart; netdata values are expressed in KB
NethServer/dev#6475
> ui. fix unit of measurement in bandwidth chart

- root/etc/e-smith/events/actions/interface-config-write-pppoe
The correct option is named LINUX_PLUGIN, see man pppoe.conf.
NethServer/dev#6500
> pppoe: fix plugin option name

- api/wan/read
- api/wan/update
- ui/public/i18n/language.json
- ui/src/views/WAN.vue
When root{EmailAddress} is empty the API use it to overwrite NotifyWanTo with an empty value
Same for NotifyWanFrom
https://github.com/NethServer/dev/issues/6497
> Firewall WAN notification for wan link down

- api/port-forward/validate
- ui/public/i18n/language.json
- ui/src/views/PortForward.vue
If port range are written to /etc/shorewall/rules in decreasing numerical order we have warnings in shorewall restart and we break the event
NethServer/dev#6509
> Port range, must be ascending numerical order

- ui/src/filters/filters.js
- ui/src/views/WAN.vue
We display the value of speedtest in Megabytes but the international value is the megabit.
If the speedtest is inferior to 1megabit we display the value in kilobits
https://github.com/NethServer/dev/issues/6513
> Display the speedtest-cli in bit format

- api/settings/update
Inside the settings page, once the settings are saved the banner to apply the change appears but it is not needed at all.
The simple fix is to remove the banner for that particular page.
https://github.com/NethServer/dev/issues/6519
> No update banner for the settings panel

- root/etc/ppp/ip-up.ppp0
If PPPoE has a dynamic IP, the restart will create port
forward rules using the new IP address.
NethServer/dev#6568
> PPPoE: always restart shorewall on interface up

- api/troubleshooting/read
If Cockpit language does not use dot as a decimal separator, then rrd data was wrong
https://github.com/NethServer/dev/issues/6590
> analysis api. fix wan and ping rrd charts

- api/troubleshooting/read
Data are stored as octets, so the value read from RRD
should be multiplied by 8
Thanks to Filippo Carletti
NethServer/dev#6599
> troubleshooting api: fix traffic chart data

- root/etc/e-smith/templates/etc/shorewall/mangle/20ndpi
- root/etc/e-smith/templates/etc/shorewall/mangle/22restore_connmark
CONNMARK is also used by the IPS, Squid and QoS, not only by nDPI.
> Always restore connmark

- api/lib/firewall_functions.pl
- ui/src/views/LocalRules.vue
- ui/src/views/Rules.vue
With separator we have had a blank page in the local-rule web page when a separator exists, this PR  fix it, but also
- red color of separator
- exception in the api when we list rules for the local-rules else the object rules is not empty and the default button `create your first local-rule` is not displayed
- exception in the api when we have no rules to not display the separator and display the default button `create your first rule`
NethServer/dev#6602
> Fix the exclusion for separator type in local-rules

- ui/src/views/TrafficShaping.vue
The bandwidth should always be displayed in bits and not bytes.
NethServer/dev#6623
See https://community.nethserver.org/t/nethserver-release-7-9-2009-problem-with-upload/19275/17?u=giacomo
> ui: fix traffic shaping chart label

- root/etc/e-smith/templates/etc/shorewall/mangle/80qos_ndpi
Due to how packets are processed, the bypass marker could be "lost".
This patch avoids saving the bypass bit on every packet to the
connection mark. The connection will be marked only once in
shorewall-rules, on exit from suricata.
NethServer/dev#6661
> Exclude IPS bypass bit (0x20) from mark saving

- root/etc/e-smith/templates/etc/shorewall/mangle/40priorities
- root/etc/e-smith/templates/etc/shorewall/mangle/80qos_ndpi
As QoS supports a maximum of 63 marks, to avoid clashes with suricata,
move the bypass mark to the highest bit (!0x80=0x7f).
NethServer/dev#6690
> Move suricata marks outside of QoS range

- api/traffic-shaping/read
Since netdata 1.35.0, the tc chart changed the name
from `<provider>_<direction>` to `<provider>-<direction>`
NethServer/dev#6695
> UI: fix traffic shaping charts

- NethServer/Firewall.pm
Shorewall provider marks are in hexadecimal format.
NethServer/dev#6752
> Fix mwan provider mark format
