NethServer/Firewall.pm, root/etc/e-smith/db/networks/migrate/multiwan.el7, root/etc/e-smith/templates/etc/shorewall/tcrules/40providers, root/usr/libexec/nethserver/providers-status
· migrate network db for multiwan: remove obslete props and create multiwan config where missing
· ignore status and description props for multiwan providers
=> new multiwan backend

root/etc/e-smith/templates/etc/shorewall/mangle/40providers
=> mangle: correctly mark packets originated from firewall. 

root/etc/e-smith/templates/etc/shorewall/rules/10base20established50ndpi, root/etc/e-smith/templates/etc/shorewall/rules/60rules
=> nDPI: auto-create reversed rules

NethServer/Database/Ndpi.pm, NethServer/Firewall.pm, root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_FirewallRules.php, root/usr/share/nethesis/NethServer/Module/FirewallRules/Index.php, root/usr/share/nethesis/NethServer/Module/FirewallRules/PickObject.php, root/usr/share/nethesis/NethServer/Template/FirewallRules/PickObject.php
List NDPI protocols among other services available on the system.
NethServer/dev#5102
=> NDPI support for Firewall Rules page NethServer/dev#5102

root/etc/e-smith/templates/etc/shorewall/rules/10base20established, root/etc/e-smith/templates/etc/shorewall/rules/10base20established90nfq
Since NFQ rule decision is final,
all NFQ rules must be evaluted at the
end of ESTABLISHED chain.
NethServer/dev#5104
NethServer/dev#5102
=> Shorewall rules: swap NFQ and nDPI rule order.

root/usr/share/nethesis/NethServer/Module/FirewallRules/Index.php, root/usr/share/nethesis/NethServer/Template/FirewallRules/PickObject.php
This is just a sample for "facebook" and "amazon" protocols.
NethServer/dev#5102
=> Show DPI protocol brand icons NethServer/dev#5102

NethServer/Firewall.pm, README.rst, root/etc/cron.d/shorewall-update-dst, root/etc/e-smith/templates/etc/shorewall/rules/10base20established50ndpi, root/etc/e-smith/templates/etc/shorewall/rules/60rules, root/usr/libexec/nethserver/shorewall-update-dst
=> Firewall rules: add support for time objects

root/etc/e-smith/templates/etc/shorewall/mangle/40providers
=> Time constraints: add support for mangle rules

root/etc/e-smith/templates/etc/shorewall/rules/10base20established90nfq
=> NFQ: add established loc2fw and fw2loc traffic

createlinks, root/etc/e-smith/validators/actions/fwrule-trafficshaping, root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_FirewallRules.php, root/usr/share/nethesis/NethServer/Module/FirewallRules/Edit.php, root/usr/share/nethesis/NethServer/Module/FirewallRules/Index.php, root/usr/share/nethesis/NethServer/Module/FirewallRules/RuleGenericController.php, root/usr/share/nethesis/NethServer/Template/FirewallRules/Index.php, root/usr/share/nethesis/NethServer/Template/FirewallRules/Rule.php
=> Traffic shaping firewall rules UI NethServer/dev#5113

root/usr/share/nethesis/NethServer/Help/en/NethServer_Module_FirewallRules.rst
* Explain different types of rules
* Added Traffic shaping
NethServer/dev#5113
=> Reworked Firewall rules inline help

root/usr/libexec/nethserver/shorewall-update-dst
=> Fix shorewall-update-dst. NethServer/dev#5107

root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_FirewallRules.php, root/usr/share/nethesis/NethServer/Module/FirewallRules/Index.php, root/usr/share/nethesis/NethServer/Template/FirewallRules/Index.php
=> Show counters on UI rule selectors

NethServer/Firewall.pm, root/usr/share/nethesis/NethServer/Tool/FirewallObjectsFinder.php
=> Fix firewall rules with vpn zone

root/etc/e-smith/events/actions/nethserver-shorewall-restart, root/etc/e-smith/templates/etc/shorewall/shorewall.conf/10init, root/usr/lib/systemd/system/shorewall.service.d/nethserver-firewall-base.conf
NethServer/dev#5193
NethServer/dev#5188
=> Bad network config inhibits shorewall startup

root/usr/share/nethesis/NethServer/Module/FirewallRules/Create.php
The TimeRaw was ignored resulting in "Always" value always assigned
during rule creation.
NethServer/dev#5200
=> Fix TimeRaw handling in rule creation

README.rst, root/etc/e-smith/db/fwrules/migrate/issue5234.ns7
=> Migrate traffic shaping rules

root/etc/e-smith/templates/etc/shorewall/rtrules/20providers
=> rtrules: move provider rules later in the routing table

root/etc/ppp/ip-down.ppp0, root/etc/ppp/ip-up.ppp0
=> PPPoE: enable provider in ip-up. NethServer/dev#5260

NethServer/Firewall.pm
=> Firewall lib: handle alias zones.

createlinks, root/etc/e-smith/events/actions/nethserver-firewall-base-condenable, root/etc/e-smith/events/actions/nethserver-firewall-base-disable, root/etc/e-smith/events/actions/nethserver-firewall-base-enable
=> Disable shorewall during restore procedure

root/etc/e-smith/events/actions/nethserver-firewall-base-condenable, root/etc/e-smith/events/actions/nethserver-shorewall-restart, root/usr/libexec/nethserver/open-sshd-running-port
=> Make sure sshd running port is always open

root/etc/e-smith/templates/etc/shorewall/modules/10base
=> modules: always load helpers

root/usr/share/nethesis/NethServer/Module/FirewallObjects/Times/Modify.php, root/usr/share/nethesis/NethServer/Module/FirewallRules/CreateTime.php
Change first day of week from Sunday to Monday in Firewall objects and rules
NethServer/dev#5326
=> Set Monday as first day of week

root/etc/e-smith/templates/etc/shorewall/stoppedrules/20running_sshd
=> stoppedrules: fix sshd running port

root/etc/e-smith/templates/etc/shorewall/stoppedrules/20running_sshd
=> Shorewall stopped rules: support multiple sshd instances

root/etc/e-smith/templates/etc/shorewall/rules/50pf, root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_PortForward.php, root/usr/share/nethesis/NethServer/Module/PortForward/Modify.php, root/usr/share/nethesis/NethServer/Template/PortForward/Modify.php
=> Implement port forward log

root/usr/share/nethesis/NethServer/Language/en/NethServer_Module_FirewallObjects.php, root/usr/share/nethesis/NethServer/Module/FirewallObjects/Services/Modify.php, root/usr/share/nethesis/NethServer/Module/FirewallRules/CreateService.php
=> UI: allow cretion of services with port range

root/etc/e-smith/templates/etc/shorewall/providers/20providers, root/etc/e-smith/templates/etc/shorewall/providers/80providers_output
Allow override of provider options.
Usefull for MLVPN usage scenario.
=> providers: refactor template

root/etc/e-smith/events/actions/interface-config-write-pppoe
=> pppoe: always enable rp-pppoe plugin

root/etc/e-smith/validators/actions/fwrule-trafficshaping
The format is changed after nethServer/dev#5484 implementation
=> fwrule-modify validator: fix tc rule check

api/connections/read, root/usr/lib/sysctl.d/conntrack.conf, ui/src/filters/filters.js, ui/src/i18n/locale-en.json, ui/src/views/Connections.vue
Speed up client side rendering.
=> ui: use table view for connections

ui/package.json, ui/src/App.vue, ui/src/directives/DocInfo.vue, ui/src/i18n/locale-en.json, ui/src/main.js, ui/src/views/About.vue, ui/src/views/Connections.vue, ui/src/views/Dashboard.vue, ui/src/views/LocalRules.vue, ui/src/views/Logs.vue, ui/src/views/Objects.vue, ui/src/views/PortForward.vue, ui/src/views/Rules.vue, ui/src/views/Settings.vue, ui/src/views/TrafficShaping.vue, ui/src/views/WAN.vue, ui/src/views/sNAT.vue, ui/vue.config.js
- Remove VueJS warning in each views
- Remove restore banner and buttons
- Remove `Expand Info` button
- Handle position on rule reorder
- Added details in TC bindto interfaces
- Removed polling of firewall status
- Added fa-angle in details view
=> Firewall UI. graphics adjustments

api/traffic-shaping/update
https://github.com/NethServer/dev/issues/5807
=> api. fixed missing Mark prop in update.

api/wan/update
The api implementation to reorder WAN policy routes was missing
https://github.com/NethServer/dev/issues/5823
=> Reordering of WAN policy routes

nethserver-firewall-base.spec, root/etc/sudoers.d/50_nsapi_nethserver_firewall_base
=> Cockpit config for sudoers delegation

ui/src/views/TrafficShaping.vue
When creating a priority rule in traffic shaping, L7 applications
now appear in "Service" suggestion input
https://github.com/NethServer/dev/issues/5846
=> L7 applications for traffic shaping rules

root/etc/sudoers.d/50_nsapi_nethserver_firewall_base
https://github.com/NethServer/dev/issues/5805
=> fix missing network api

ui/public/i18n/language.json
https://github.com/NethServer/dev/issues/5856
=> i18n: fix typo

ui/src/views/TrafficShaping.vue
Firewall object can be the source of a traffic shaping rule
https://github.com/NethServer/dev/issues/5864
=> Firewall object in traffic shaping rules

ui/public/i18n/language.json, ui/src/views/Logs.vue
Logs page now has the same look and feel as the others Cockpit modules
https://github.com/NethServer/dev/issues/5866
=> Logs: refactored logs page

ui/src/views/LocalRules.vue
=> ui. allow all services for local rules

api/lib/firewall_functions.php
=> api. allow fwservice in validate of local rules

api/objects/validate, ui/public/i18n/language.json, ui/src/views/Objects.vue
=> ui. fix missing translations

api/traffic-shaping/validate, root/etc/e-smith/db/tc/migrate/issue5897, ui/public/i18n/language.json, ui/src/views/TrafficShaping.vue
=> Fix FireQoS class unit usage 

api/objects/read, ui/public/i18n/language.json, ui/src/views/Objects.vue
=> Prevent DNS/DHCP record modification

createlinks, root/etc/e-smith/templates/etc/shorewall/blrules/10base, root/etc/e-smith/templates/etc/shorewall/initdone/10base
Both templates are used by fail2ban 0.10
See stephdl/nethserver-fail2ban#1
NethServer/dev#5943
=> Add blrules and initdone templates

nethserver-firewall-base.spec, root/etc/profile.d/network-recovery.sh, root/etc/systemd/system/network.service.d/network-recovery-cleanup.conf, root/usr/sbin/network-recovery
https://github.com/NethServer/dev/issues/5874
=> Network-recovery tool implementation

api/wan/read, ui/public/i18n/language.json, ui/src/views/WAN.vue
Refer to https://github.com/NethServer/dev/issues/5956
=> ui. show ip address on multiwan active backup configuration

createlinks, root/etc/e-smith/templates/etc/shorewall/stopped/10base
https://github.com/NethServer/dev/issues/5943
=> Template for shorewall stopped script

ui/public/i18n/language.json, ui/src/views/LocalRules.vue
Show network services policies in **Local Rules** page
https://github.com/NethServer/dev/issues/6007
=> Network services policies in Local Rules page

ui/src/views/LocalRules.vue
Show network services in *Local Rules* page if no local rule is defined
https://github.com/NethServer/dev/issues/6007
https://github.com/NethServer/nethserver-firewall-base/pull/125
=> Local rules: show network services with no local rule defined

ui/src/views/LocalRules.vue
Fixed network services tooltip, which sometimes was not fully visible
NethServer/dev#6007
https://github.com/NethServer/nethserver-firewall-base/pull/126
=> Local rules: fixed network services tooltip position

ui/src/views/Rules.vue
=> ui. fix missing log checkbox in rule creation

ui/public/i18n/language.json
=> UI: fix description of port forward syntax

api/wan/read
Correctly retrieve PPPoE address, better error handling.
NethServer/dev#6048
=> api wan: fix speedtest on ppp0

root/etc/e-smith/templates/etc/shorewall/rules/50pf, root/etc/e-smith/templates/etc/shorewall/snat/51pflanmasq
Amend bug introduced by #133 
NethServer/dev#6066
=> Fix hairpin

ui/src/views/Dashboard.vue
Display hotspot interface with a proper icon and a distinctive color in Firewall dashboard
https://github.com/NethServer/dev/issues/6186
=> Network topology: Properly show hotspot interface

api/wan/read, ui/src/views/WAN.vue
- Show interface label in WAN rules, if present
- Show *PPPoE* for PPPoE interfaces
NethServer/dev#6190
=> Show interface label in WAN rules

ui/src/views/Rules.vue
=> ui: preserve Description on rule enable/disable

ui/package-lock.json, ui/package.json, ui/src/main.js, ui/src/views/Connections.vue, ui/src/views/Dashboard.vue, ui/src/views/Objects.vue
=> ui: upgrade vue-good-table to version ^2.19.3

ui/src/views/LocalRules.vue, ui/src/views/Rules.vue
Unregister listener for "changes-applied" event when leaving route
NethServer/dev#6275
=> Fix apply firewall changes event

ui/src/views/WAN.vue
https://github.com/NethServer/dev/issues/6274
=> Description added to the rule object

api/lib/firewall_functions.php, ui/public/i18n/language.json, ui/src/views/LocalRules.vue
https://github.com/NethServer/dev/issues/6277
please review 
- I translated `any` in the place holder, not sure it is a good ide
- Maybe for `rule` we could add also a place holder for the service suggestions
=> Local rules: relax the service validator to any

api/lib/firewall_functions.php, api/lib/firewall_functions.pl, ui/public/i18n/language.json, ui/src/views/LocalRules.vue, ui/src/views/Rules.vue
when you create or duplicate a rule, then you can decide to create it at the top or at the bottom of the list.
If it worth it I can do it for the local-rules
what do you think @gsanchietti 
trello card : https://trello.com/c/6Q5PyQng/219-migliorie-interfaccia-firewall
https://github.com/NethServer/dev/issues/6284
=> Firewall rule: create rule at the top of the list

api/port-forward/validate, ui/public/i18n/language.json, ui/src/views/PortForward.vue
This PR attempts to make some validation in the textarea for the property Allow.
allow list of IP or list of CIDR
https://github.com/NethServer/dev/issues/6296
=> Firewall port forward : Validation of Allow property

ui/public/i18n/language.json, ui/src/views/PortForward.vue
Improve value for `Allow Public IPs` field inside Port Forward table view.
NethServer/dev#6296
Original:
New:
=> ui: improve PF table view

api/lib/firewall_functions.php, ui/public/i18n/language.json, ui/src/views/Rules.vue
A NDPI rule cannot be rejected, the only good  options are drop and accept 
this PR is linked  to the issue https://github.com/NethServer/dev/issues/6365 for the validation
https://github.com/NethServer/dev/issues/6367
=> the ndpi rules cannot be rejected

nethserver-firewall-base.json, nethserver-firewall-base.spec, ui/src/views/About.vue
Reverts NethServer/nethserver-firewall-base#168
NethServer/dev#6388
=> Revert "Fix removal"

api/lib/firewall_functions.pl, ui/src/views/WAN.vue
- Fix command to retrieve gateway for DHCP and PPPoE interfaces
- Minor UI enhancements
NethServer/dev#6425
=> api & ui. fix gateway IP retrieval in WAN page

api/lib/firewall_functions.pl
Old command didn't work with two or more red interfaces using DHCP
NethServer/dev#6425
=> api. fix command to retrieve DHCP server

ui/src/views/Rules.vue
Show policies modal even if no firewall rules are saved.
Refer to https://github.com/NethServer/dev/issues/6432
=> ui. show policies modal even with no rules

ui/src/views/WAN.vue
Added "Close" button for speedtest popup.
Refer to https://github.com/NethServer/dev/issues/6435
=> ui. make speedtest popover closable

api/objects/validate, ui/public/i18n/language.json
Added using check before remove the service
Refer to https://github.com/NethServer/dev/issues/6439
=> api. avoid service removing if in use

api/snat/validate, root/etc/e-smith/templates/etc/shorewall/snat/20snat, ui/public/i18n/language.json, ui/src/views/sNAT.vue
Support host groups, CIDR subnets and IP ranges in sNAT
NethServer/dev#6449
=> api & ui. support multiple fw objects in sNAT

NethServer/Firewall.pm, ui/public/i18n/language.json, ui/src/views/sNAT.vue
- While deleting a firewall object, ensure it is not used as SNAT source object
- Add inline documentation
NethServer/dev#6457
=> SNAT improvemets

root/etc/e-smith/templates/etc/shorewall/mangle/20ndpi
=> Restore connmark only if packet mark is 0

NethServer/Firewall.pm, README.rst, root/etc/e-smith/db/configuration/defaults/firewall/AnyPlus
Any destination was meant to be any+ for intra-zone traffic.
=> Use any+ instead of any

ui/src/views/WAN.vue
Convert bits to bytes before to display them in the popover
https://github.com/NethServer/dev/issues/6502
=> Convert bits to bytes for speedtest-cli

api/wan/read, api/wan/update, root/etc/e-smith/db/configuration/migrate/SetDefaultValue2NotifyWan, ui/src/views/WAN.vue
We revert the change, we go back to use NotifyWanTo and NotifyWanFrom
https://github.com/NethServer/dev/issues/6497
=> NotifyWan down with firewall NotifyWanTo

nethserver-firewall-base.json
Better fit on white label installations
NethServer/dev#6510
=> cockpit manifest: remove NethServer word

ui/src/views/About.vue
=> UI: honor URLs from manifest

root/etc/e-smith/templates/etc/shorewall/rtrules/30nat, root/etc/e-smith/templates/etc/shorewall/snat/20snat, ui/src/views/sNAT.vue
Changes:
- rtrules: support multiple objects
- rtrules: prevent error on rules with IP ranges
- snat: drop support for rules with IP ranges
- ui: drop support for rules with IP range
NethServer/dev#6575
=> Fix sNAT behavior with firewall objects

api/troubleshooting/read, ui/src/components/TroubleshootingNetwork.vue
- Services tab: fix reading of interface status file; it contains a trailing newline
- Network tab: fix interface down icon
NethServer/dev#6593
=> analysis api. fix multiwan status

root/etc/sudoers.d/50_nsapi_nethserver_firewall_base
Allow access for non-root users
NethServer/dev#6603
=> sudo: add troubleshooting API

.transifex.sh, .travis.yml
https://github.com/NethServer/dev/issues/6629
the secret `TRANSIFEX_API_TOKEN` must be set in this repository
=> Automatic push Once the PR has been merged

ui/src/components/TroubleshootingHosts.vue, ui/src/components/TroubleshootingNetwork.vue
Explicitly free memory used by Dygraph at every chart update
https://github.com/NethServer/dev/issues/6648
=> Fix Dygraph memory leak

ui/src/components/TroubleshootingNetwork.vue
=> UI: fix ping charts

root/etc/e-smith/validators/actions/fwobject-hostgroup-remove-member
Referer to: https://github.com/NethServer/dev/issues/6735
=> Fix host-group member deletion
